@startuml context_diagram
!include <C4/C4_Context.puml>

title Context diagram for SmartHome System

Person(user, "User", "Uses the SmartHome system to manage house heating and get current temperature data")
Person(installationTechnician, "Installation Technician", "Installs the equipment and performs the initial connection of user's smart home system")

System_Ext(switch, "SmartHome Switcher", "Physical device installed in user's house. Turns on/off heating")
System_Ext(sensor, "SmartHome Sensor", "Physical device installed in user's house. Measures and transmits temperature")

System_Boundary(system, "Smart Home System") {
    System(app, "SmartHome System", "Allows users to manage home heating and receive data from sensors")
}

Rel(installationTechnician, switch, "Installs and performs initial system connection")
Rel(installationTechnician, sensor, "Installs and performs initial system connection")
Rel(user, app, "Manages heating and receives house temperature")
Rel(app, switch, "Commands to turn on/off heating")
Rel(sensor, app, "Sends telemetry data")

@enduml