@startuml
!define ER

entity User {
    *id : int
    username : string
    email : string
    password : string
    status : enum
}

entity House{
    *id : int
    name : string
    user_id : int
}

entity Location {
    *id : int
    name : string
    house_id : int
}

entity Device {
    *id : int
    type_id : int
    status : enum
    model : string
    name : string
    serial_number : string
    mac_address : string
    location_id : int
    manufacturer_id : int
    firmware_id : int
}

entity DeviceData{
    *id : int
    device_id : int
    device_status : int
}

entity DeviceEvent{
    *id : int
    device_id : int
    event : text/json
    created_at : datetime
}

entity DeviceTelemetry{
    *id : int
    device_id : int
    telemetry_type_id: int
    value: string
    sent_at : datetime
}

entity TelemetryType {
    *id : int
    code : string
    name : string
    unit : string
    data_type : string
    description : string
}

entity Scenario {
    *id : int
    trigger_id : int
    device_id : int
    action_id : int
}

entity Trigger{
    *id : int
    scenario_id : int
    type : enum(time, event)
    parameters : text
}

entity Action {
    *id : int
    scenario_id : int
    device_type_id : int
    type : text
    parameters : text
}

entity DeviceType {
    *id : int
    code : string
    name : string
}

entity DeviceAction {
    *id : int
    device_type : int
    code : string
    name : string
}

entity Manufacturer {
    *id : int
    name : string
    country : string
}

entity Firmware {
    *id : int
    version : string
    release_date : date
    description : string
}

User ||--o{ House : user
House ||--o{ Location : location
Location ||--o{ Device : device
DeviceType ||--o{ Device : type
DeviceData ||--o{ Device : id
DeviceEvent ||--o{ Device : id
DeviceTelemetry ||--o{ Device: id
DeviceTelemetry ||--o{ TelemetryType: type
Firmware ||--o{ Device : firmware
Manufacturer ||--o{ Device : manufacturer
Scenario ||--o{ Device : type
Scenario ||--o{ Trigger : scenario
Action ||--o{ Scenario : action 
DeviceType ||--o{ DeviceAction: type

@enduml